/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View.Compra;

import DAO.CompraDAO;
import DAO.FornecedorDAO;
import javax.swing.JOptionPane;
import DAO.ProdutoDAO;
import Model.CompraModel;
import Model.FornecedorModel;
import Model.ItemCompraModel;
import Model.ProdutoModel;

/**
 *
 * @author forster
 */
public class FrmRealizarCompra extends javax.swing.JFrame {

    private CompraModel compraModel;
    /**
     * Creates new form FrmCadastrarEndereco
     */
    public FrmRealizarCompra() {
        initComponents();
        
        String[] sourceFornecedorComboBox = new FornecedorDAO().GetAllComboBox();
        
        for(var fornecedor : sourceFornecedorComboBox){
            comboBoxFornecedor.addItem(fornecedor);
            
        }
        
        String[] sourceListaCompraProdutos = new ProdutoDAO().GetAllJList();
        
        listaCompraProdutos.setListData(sourceListaCompraProdutos);
        
        compraModel = new CompraModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaCompraProdutos = new javax.swing.JList<>();
        comboBoxFornecedor = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        fieldCompraQuantidade = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel1.setText("Realizar Compra");

        jLabel2.setText("Fornecedor");

        jLabel3.setText("Produto");

        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Comprar produto");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        listaCompraProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaCompraProdutosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listaCompraProdutos);

        comboBoxFornecedor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                comboBoxFornecedorFocusLost(evt);
            }
        });
        comboBoxFornecedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                comboBoxFornecedorMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                comboBoxFornecedorMouseReleased(evt);
            }
        });

        jLabel4.setText("Quantidade");

        jButton3.setText("Finalizar Compra");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(280, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(214, 214, 214))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboBoxFornecedor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(fieldCompraQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(comboBoxFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fieldCompraQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2)
                            .addComponent(jButton3))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jLabel3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    
    if(compraModel.getFornecedor() == null){
        
        String[] fornecedor = comboBoxFornecedor.getSelectedItem().toString().split(" - ");
    
        FornecedorModel fornecedorModel = new FornecedorModel(fornecedor[1], null, null, fornecedor[2]);
        
        fornecedorModel.setId(Integer.parseInt(fornecedor[0]));
        
        compraModel.setFornecedor(fornecedorModel);
    }
    
    
    String[] produto = listaCompraProdutos.getSelectedValue().split(" - ");
    
    ProdutoModel produtoModel = new ProdutoModel(
            produto[1], 
            Double.parseDouble(produto[2].replace("Valor Unitário: R$", "")), 
            produto[3].replace("Qtde Estoque: ",""));
    
    produtoModel.setId(Integer.parseInt(produto[0]));
    
    ItemCompraModel itemCompraModel = new ItemCompraModel(
            produtoModel, 
            Integer.parseInt(fieldCompraQuantidade.getText()), 
            compraModel);
    
    compraModel.getProdutos().add(itemCompraModel);
    
    JOptionPane.showMessageDialog(null, "Produto comprado. \nValor Total: R$ " + itemCompraModel.getValorTotal(), "SUCESSO", 2);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void listaCompraProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaCompraProdutosMouseClicked
         fieldCompraQuantidade.setText("");
    }//GEN-LAST:event_listaCompraProdutosMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // finalizar compra
        
        CompraDAO compraDAO = new CompraDAO();
        
        boolean resultado = compraDAO.create(compraModel);
        
        if(resultado){
            JOptionPane.showMessageDialog(null, "Compra realizada com sucesso.", "SUCESSO", 2);
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(null, "Erro ao realizar compra.", "ERRO", 2);
            this.dispose();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void comboBoxFornecedorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboBoxFornecedorMouseExited
        //comboBoxFornecedor.setEnabled(false);
    }//GEN-LAST:event_comboBoxFornecedorMouseExited

    private void comboBoxFornecedorMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboBoxFornecedorMouseReleased
        //comboBoxFornecedor.setEnabled(false);
    }//GEN-LAST:event_comboBoxFornecedorMouseReleased

    private void comboBoxFornecedorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_comboBoxFornecedorFocusLost
        comboBoxFornecedor.setEnabled(false);
    }//GEN-LAST:event_comboBoxFornecedorFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmRealizarCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmRealizarCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmRealizarCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmRealizarCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmRealizarCompra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboBoxFornecedor;
    private javax.swing.JTextField fieldCompraQuantidade;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listaCompraProdutos;
    // End of variables declaration//GEN-END:variables
}
